version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    volumes:
      - ${VOLUME_PATH}/plex-config:/config
      - ${MEDIA_VOLUME_PATH}/media:/data
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    ports:
      - 32400:32400
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055"
    volumes:
      - ${VOLUME_PATH}/overseerr-config:/app/config
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_PATH}/radarr-config:/config
      - ${MEDIA_VOLUME_PATH}/media:/media
      - ${MEDIA_VOLUME_PATH}/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_PATH}/sonarr-config:/config
      - ${MEDIA_VOLUME_PATH}/media:/media
      - ${MEDIA_VOLUME_PATH}/downloads:/downloads
    restart: unless-stopped

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${VOLUME_PATH}/tautulli-config:/config
    environment:
      - PLEX_URL=http://plex:32400
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${VOLUME_PATH}/bazarr-config:/config
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ${VOLUME_PATH}/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${VOLUME_PATH}/nzbget-config:/config
      - ${VOLUME_PATH}/nzbget-downloads:/downloads
    restart: unless-stopped
